package SnakeGame;
import SnakeGame.View.MenuScene;
import SnakeGame.View.SceneManager;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import javafx.application.Application;
import javafx.geometry.Rectangle2D;
import javafx.stage.Screen;
import javafx.stage.Stage;

public class App extends Application {
    private static Rectangle2D screenBounds = Screen.getPrimary().getVisualBounds();
    private static final double screenWidth= screenBounds.getWidth();;
    private static final double screenHeight=screenBounds.getHeight();
    public static double getScreenWidth(){
        return screenWidth;
    }
    public static double getScreenHeight(){
        
        return screenHeight;
    }
    @Override
    public void start(Stage stage) {
        SceneManager sceneManager = SceneManager.getInstance();
        sceneManager.setPrimaryStage(stage);
        sceneManager.changeScene(new MenuScene());
        sceneManager.show();
    }

    
    public static void main(String[] args) {
        launch();
    }
    public Object getGreeting() {
        return 12;
    }
}
